opt_in_rules:
  - empty_string

disabled_rules:
  - unused_closure_parameter
  - trailing_comma
  - line_length
  - trailing_newline
  - todo
  - file_length
  - force_try
  - force_cast
  - function_body_length
  - function_parameter_count
  - large_tuple
  - type_body_length
  - type_name # allow any length
  - cyclomatic_complexity # allow complex if/switch/for
  - identifier_name # allow `_`-prefixed variable name
  - nesting # allow multiple type nesting
  - weak_delegate # delegate may be a separated class that needs to be retained by core class.
  - colon
  - multiple_closures_with_trailing_closure
  - private_over_fileprivate
  - fallthrough

  # TODO: enable this
  - vertical_parameter_alignment
  - redundant_string_enum_value
  - legacy_constructor
  - implicit_getter
  - syntactic_sugar
  - for_where

included:
  - AbemaTutorial
  - AbemaTutorialTests

custom_rules:
  const_declare_use_enum:
    name: "Use enum instead of struct."
    regex: 'struct\sConst\w*'
    message: "Use enum Const instead, if you want to declare constant values."
    severity: warning
    match_kinds: identifier

  constants_declare_use_const:
    name: "Rename Constant[s] to Const."
    regex: '(enum|struct)\sConst\w+'
    message: "Use Const instead of Constants and Constant."
    severity: warning
    match_kinds: identifier

  function_argument_label_spacing:
    name: "Add white space."
    regex: '\([^:\[\)]+:[^\s\):]+\)'
    message: "White space should be next to the colon of function argument label."
    severity: warning
    match_kinds:
      - identifier
      - keyword
      - number

  subscribe_use_subscribe_on_next:
    name: "Use subscribe(onNext:)."
    regex: 'bind\(onNext:\s+'
    message: "Use subscribe(onNext:), if you want to subscribe the stream."
    severity: warning
    match_kinds: identifier
